<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id'])) {
    $id = ' id="' . $this->siteId . '_' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->zoneconfig['conf']['melisKey'];
}
?>

<?php if(!empty($this->siteId)) { ?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane widget-body-regular meliscms_center_tabs">
    <div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
        <div class="widget-body innerAll inner-2x">
            <div class="tab-header-title-container">
                <div class="row">
                    <div class="col-md-12">
                        <h3 class="float-left"><?= $this->translate('tr_meliscmspagescripteditor_title'); ?></h3>
                    </div>
                </div>
            </div>
            <div class="tab-pane active">
                <div class="row">
                    <div class="col-md-12">
                        <?php
                            //render the script form
                            $scriptForm = $this->scriptForm;
                            $scriptForm->prepare();
                            $scriptForm->setAttribute('id', $scriptForm->getAttribute('id'));
                            
                            echo $this->form()->openTag($scriptForm);
                            echo $this->melisFieldCollection($scriptForm);
                            echo $this->form()->closeTag();
                            
                            //render the exception form
                            $scriptExceptionForm = $this->scriptExceptionForm;
                            $scriptExceptionForm->prepare();
                            $scriptExceptionForm->setAttribute('id', $scriptExceptionForm->getAttribute('id'));
                            
                            echo $this->form()->openTag($scriptExceptionForm);
                            echo $this->melisFieldCollection($scriptExceptionForm);
                            echo $this->form()->closeTag();
                        ?>  
                    </div>
                </div>      
            </div>

            <div class="row">
                <div class="col-md-12">
                    <?php
                        if (!empty($this->zoneconfig['interface'])) {
                            foreach ($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
                                echo $this->$keyConfig;
                            }
                        }
                    ?>
                </div>
            </div> 
        </div>
    </div>    
</div>
<?php } ?>
