<div class="col-md-12">  
    <?php
        $scriptForm = $this->scriptForm;
        $scriptForm->prepare();
        $scriptForm->setAttribute('id', $scriptForm->getAttribute('id'));
        
        echo $this->form()->openTag($scriptForm);
        echo $this->melisFieldCollection($scriptForm);
        echo $this->form()->closeTag();
    ?>            

    <div class='page-edition-script-exception-form'>
        <h4><?php echo $this->translate('tr_meliscmspagescripteditor_page_edition_exception_title')?></h4>
        <p><?php echo $this->translate('tr_meliscmspagescripteditor_page_edition_exception_desc')?></p>

         <?php
            $exceptionForm = $this->exceptionForm;
            $exceptionForm->prepare();
            $exceptionForm->setAttribute('id', $exceptionForm->getAttribute('id'));            
            echo $this->form()->openTag($exceptionForm); ?>

      <?php
        foreach ($exceptionForm->getElements() as $key => $val) {   ?>
            <div class="form-group">                
                <?php 
                    if ($key == 'mcse_exclude_site_scripts') { ?>                        
                        <div class="checkbox cb-cont melis-cms-page-script-checkbox">
                           <label class="page-edition-site-script-input-checkbox-label">
                                <span class="cbmask-outer">
                                    <span class="cbmask-inner <?=!empty($mcse_exclude_site_scripts) ? 'cb-active' : ''?>"></span>
                                </span>
                                <input type="hidden" name="<?=$key?>" value="0" >
                                <input type="checkbox" name="<?=$key?>" class="page-edition-site-script-input-checkbox" id="<?=$val->getAttribute('id');?>" value="1" <?=!empty($mcse_exclude_site_scripts) ? 'checked' : ''?>> <?=$val->getLabel(); ?>
                           </label>
                        </div>                       
                <?php   } elseif ($key == 'mcse_id') { ?>
                            <input type="hidden" name="<?=$key?>" id="<?=$key?>" value="<?=$val->getValue()?>" >
                <?php }
                ?>                               
            </div>
        <?php } ?>      

        <?php    echo $this->form()->closeTag();
        ?>             
    </div>   
</div>
