<?php
    $id = '';
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->idPage . '_' . $this->zoneconfig['conf']['id'] . '"';
        $data_melisKey = $this->zoneconfig['conf']['melisKey'];
?>

<div <?= $id; ?> data-melisKey='<?= $data_melisKey; ?>' class="meliscms_center_tabs tab-pane widget-parent melisToolContainer clearfix">
    <input type = 'hidden' name = 'pageEditionScriptEditorPageId' id = 'pageEditionScriptEditorPageId' value = "<?=$this->idPage?>" >
    <div class="col-md-12">
        <div class="widget row widget-inverse">
            <div class="widget-body">
                <div class="row">
                    <?php
                        if (!empty($this->zoneconfig['interface'])) {
                            foreach ($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
                                echo $this->$keyConfig;
                            }
                        }
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>

